### ISSUE TITLE
不好意思，请问一下release的exe怎么使用啊？

### ISSUE THREAD

**Issue by jjjjax** [Presburger/qmc-decoder#1]
直接运行 小黑屏窗口一闪就没了.

**Comment by presburger** [comment]
比如你的qmcflac文件是暗香.qmcflac。把这个qmcflac文件和decoder.exe放到D盘，然后打开windows的cmd,执行：
```
>>d:
>>decoder.exe 暗香.qmcflac
```
PS：这周末我会改一个版本可以自动化批量在windows上转换

**Comment by jjjjax** [comment]
谢谢，懂了.
