### ISSUE TITLE
Why isn't Android supported?

### ISSUE THREAD

**Issue by huzpsb** [Presburger/qmc-decoder#11]
Sorry but I have no idea in how to converting a C++ code into an application for android?

**Comment by panjiangyi** [comment]
Do you guys not have computers?

**Comment by huzpsb** [comment]
> Do you guys not have computers?

yes,we do,but we don't use it often

**Comment by ghost** [comment]
Download the Linux version and use a terminal app like Termux

**Comment by huzpsb** [comment]
@ygsk10 I know exactly what wine_with_termux can do,however,it sounds like you want your mobile lose respond than use this applications properly.

**Comment by ghost** [comment]
> @ygsk10 I know exactly what wine_with_termux can do,however,it sounds like you want your mobile lose respond than use this applications properly.

都是中国人
安卓是可以直接用Linux版本的（不是windows模拟器），我刚才编译了一份，有没有qmc文件测试一下
<img>https://i.loli.net/2020/02/04/A1Uq9DeG85SrPJF.png</img>
文件可以上传到anonfile.com或者send.firefox.com

**Comment by huzpsb** [comment]
@ygsk10 ~~我太懒了~~,所以我用的是wine+termux整合包QwQ

**Comment by ygsk10** [comment]
> @ygsk10 ~我太懒了~,所以我用的是wine+termux整合包QwQ

然后lose respond？

**Comment by huzpsb** [comment]
@ygsk10 ram+cpu 100%,一分钟后我关了

**Comment by ghost** [comment]
> @ygsk10 ram+cpu 100%,一分钟后我关了


> 我刚才编译（下载源码然后pkg install boost boost-static cmake，按readme流程，decoder文件copy到$HOME执行）了一份，有没有qmc文件测试一下
