### ISSUE TITLE
启动程序之后就停止运行了

### ISSUE THREAD

**Issue by gaigeshen** [Presburger/qmc-decoder#13]
![image](https://user-images.githubusercontent.com/7309579/61441747-d8348100-a978-11e9-9a75-68c0247cc9e3.png)

![image](https://user-images.githubusercontent.com/7309579/61441785-e97d8d80-a978-11e9-9b32-366160c68ca0.png)

**Comment by presburger** [comment]
windows版本我周末重新编译一下

**Comment by presburger** [comment]
使用的时候，注意一下最好qmc文件的目录下不要有文件夹。
