### ISSUE TITLE
在mac上不能正常运行

### ISSUE THREAD

**Issue by willyuewu** [Presburger/qmc-decoder#15]
感谢制作这个转换程序！
今天在找音乐的时候发现了这个程序，想把QQ音乐下载的内容转换成mp3或者flac，但是一直无法正常运行。我把.command和可执行程序都拷贝到了qmc的文件夹，但是运行始终是下图的结果：
![~ 2019-07-27 at 19 29 44](https://user-images.githubusercontent.com/35925230/61993886-3b26c600-b0a5-11e9-8777-a5de2b4e5088.jpg)
我以为是文件夹权限的问题或者文件名是日文的问题，但修改了之后也不能正常工作。
系统版本是10.15Beta4，不知道和这个有没有关系。
谢谢！

**Comment by presburger** [comment]
请问你下载的是最新的release版本吗？

**Comment by willyuewu** [comment]
是的 就是1.50的release。
谢谢回复

**Comment by presburger** [comment]
尝试在命令行中直接执行试试
```shell
cd <qmc dir>
chmod a+x decoder
./decoder
```

**Comment by willyuewu** [comment]
这样就可以运行了 感谢帮助！
文件名是日文也不影响
