### ISSUE TITLE
转换这两个文件会闪退

### ISSUE THREAD

**Issue by YandLiu** [Presburger/qmc-decoder#16]
文件已上传至Firefox Send
https://send.firefox.com/download/c317445cec75fd57/#10pL20xz-pPaGKR6RHwkfg

**Comment by presburger** [comment]
谢谢，我抽时间看一下

**Comment by presburger** [comment]
@YandLiu 是windows闪退还是其他操作系统？

**Comment by YandLiu** [comment]
Windows 7 x64

**Comment by YandLiu** [comment]
现在换到了Win10，也会闪退

**Comment by YandLiu** [comment]
1.5.0还是闪退
补个链接：https://www.lanzous.com/i7eprve

**Comment by presburger** [comment]
谢谢你的反馈，后续会修复（PS：貌似现在腾讯QQ音乐以及放弃QMC格式了）。
祝好

YandLiu <notifications@github.com> 于2019年11月17日周日 上午9:20写道：
