### ISSUE TITLE
win10下运行程序无反应

### ISSUE THREAD

**Issue by Lawrence-Opensource** [Presburger/qmc-decoder#17]
运行程序后无法识别文件。

![{992C541A-508B-4696-99E8-7D69EE9FA087} png](https://user-images.githubusercontent.com/55101368/64548244-d11a6580-d360-11e9-988d-8cd7c3be7fd7.jpg)
![Uploading {992C541A-508B-4696-99E8-7D69EE9FA087}.png.jpg…]()
![{683540E1-6FBC-4EA7-97E6-9213BECCB1FA} png](https://user-images.githubusercontent.com/55101368/64548245-d1b2fc00-d360-11e9-883a-9df4bdea0183.jpg)

**Comment by tsukiyokon** [comment]
我发现只要目录里有一首歌是韩文名字就会闪推

**Comment by Akarinnnnn** [comment]
建议char8_t嗷

**Comment by SHIELDA113** [comment]
Windows 10 英文家庭版1909，在VipSongsDownload下转换名字带日语的歌曲无反应，将目标歌曲和decoder.exe放进新建文件夹中再次运行即可
