### ISSUE TITLE
CMake Error: The following variables are used in this project, but they are set to NOTFOUND

### ISSUE THREAD

**Issue by mikazukimei** [Presburger/qmc-decoder#20]
After I run cmake it shows me
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Boost_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /Users/arthurwei/Downloads/qmc-decoder-master
   used as include directory in directory /Users/arthurwei/Downloads/qmc-decoder-master
   used as include directory in directory /Users/arthurwei/Downloads/qmc-decoder-master

-- Configuring incomplete, errors occurred!

**Comment by mikazukimei** [comment]
I am using mac

**Comment by presburger** [comment]
> I am using mac

brew install boost
