### ISSUE TITLE
编译出错，我还是等更新二进制文件吧QAQ

### ISSUE THREAD

**Issue by MisakaAI** [Presburger/qmc-decoder#28]
Microsoft (R) 程序维护实用工具 14.23.28107.0 版
版权所有 (C) Microsoft Corporation。  保留所有权利。

Scanning dependencies of target decoder
[ 50%] Building CXX object CMakeFiles/decoder.dir/src/decoder.cpp.obj
cl: 命令行 warning D9002 :忽略未知选项“-pipe”
cl: 命令行 warning D9002 :忽略未知选项“-std=c++17”
decoder.cpp
The contents of <filesystem> are only available with C++17 or later.
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(26): error C2039: “filesystem”: 不是“std”的成员
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.23.28105\include\regex(55): note: 参见“std”的声明
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(26): error C2878: “filesystem”: 该名称的命名空间或类不存在
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(84): error C2653: “fs”: 不是类或命名空间名称
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(84): error C3861: “path”: 找不到标识符
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(84): error C3861: “status”: 找不到标识符
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(84): error C2065: “owner_write”: 未声明的标识符
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(85): error C2653: “fs”: 不是类或命名空间名称
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(85): error C2065: “none”: 未声明的标识符
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(93): error C2653: “fs”: 不是类或命名空间名称
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(93): error C2065: “recursive_directory_iterator”: 未声明的标识符
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(93): error C2146: 语法错误: 缺少“;”(在标识符“i”的前面)
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(93): error C2143: 语法错误: 缺少“;”(在“{”的前面)
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(93): error C2143: 语法错误: 缺少“)”(在“{”的前面)
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(93): error C3861: “path”: 找不到标识符
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(93): error C2143: 语法错误: 缺少“;”(在“}”的前面)
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(93): error C2059: 语法错误:“,”
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(93): error C2065: “i”: 未声明的标识符
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(93): error C2065: “end”: 未声明的标识符
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(93): error C2065: “i”: 未声明的标识符
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(93): error C2059: 语法错误:“)”
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(94): error C2062: 意外的类型“auto”
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(95): error C2653: “fs”: 不是类或命名空间名称
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(95): error C2065: “i”: 未声明的标识符
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(95): error C3861: “status”: 找不到标识符
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(95): error C2065: “owner_read”: 未声明的标识符
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(96): error C2653: “fs”: 不是类或命名空间名称
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(96): error C2065: “none”: 未声明的标识符
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(97): error C2653: “fs”: 不是类或命名空间名称
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(97): error C2065: “i”: 未声明的标识符
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(97): error C3861: “is_regular_file”: 找不到标识符
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(97): error C2065: “file_path”: 未声明的标识符
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(98): error C2065: “file_path”: 未声明的标识符
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(98): error C2672: “std::vector<std::string,std::allocator<_Ty>>::emplace_back”: 未找到匹配的重载函数
        with
        [
            _Ty=std::string
        ]
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(105): error C2059: 语法错误:“for”
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(105): error C2143: 语法错误: 缺少“)”(在“;”的前面)
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(105): error C2143: 语法错误: 缺少“;”(在“<”的前面)
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(105): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(105): error C2059: 语法错误:“++”
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(105): error C2059: 语法错误:“)”
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(105): error C2143: 语法错误: 缺少“;”(在“{”的前面)
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(105): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(115): error C2059: 语法错误:“for”
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(115): error C2059: 语法错误:“)”
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(115): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(115): error C2371: “td_group”: 重定义；不同的基类型
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(103): note: 参见“td_group”的声明
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(116): error C2065: “td”: 未声明的标识符
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(116): error C2059: 语法错误:“;”
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(117): error C2059: 语法错误:“}”
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(117): error C2143: 语法错误: 缺少“;”(在“}”的前面)
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(120): error C2059: 语法错误:“}”
C:\Users\lolis\Music\VipSongsDownload\qmc-decoder\src\decoder.cpp(120): error C2143: 语法错误: 缺少“;”(在“}”的前面)
NMAKE : fatal error U1077: “C:\PROGRA~2\MICROS~1\2019\BUILDT~1\VC\Tools\MSVC\1423~1.281\bin\Hostx86\x86\cl.exe”: 返回代码“0x2”
Stop.
NMAKE : fatal error U1077: “"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.23.28105\bin\HostX86\x86\nmake.exe"”: 返回代码“0x2”
Stop.
NMAKE : fatal error U1077: “"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.23.28105\bin\HostX86\x86\nmake.exe"”: 返回代码“0x2”
Stop.

**Comment by presburger** [comment]
哎，怪我，MSVC的编译ARGS和GCC不一样

**Comment by imbakings** [comment]
> 哎，怪我，MSVC的编译ARGS和GCC不一样

大佬能出个二进制文件嘛，重装电脑了没环境

**Comment by imbakings** [comment]
> 哎，怪我，MSVC的编译ARGS和GCC不一样

重装了c环境，跟上面报的错一样，请问该怎么解决

**Comment by Akarinnnnn** [comment]
好消息，CMake支持C++17了

**Comment by Leroscox** [comment]
> > 哎，怪我，MSVC的编译ARGS和GCC不一样
> 
> 重装了c环境，跟上面报的错一样，请问该怎么解决

Mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0 的二进制文件存在问题，只能等更新版本解决。现在可以先用 MSVC 进行编译，已成功。

**Comment by Leroscox** [comment]
同遇到了这个问题，已解决，修改已包含在[此 PR 中](https://github.com/Presburger/qmc-decoder/pull/31)。
