### ISSUE TITLE
Mac 编译后没有decoder.command这个文件

### ISSUE THREAD

**Issue by joket1999** [Presburger/qmc-decoder#32]
Mac 编译后没有decoder.command这个文件，只有这些：

├── CMakeCache.txt
├── CMakeFiles
├── Makefile
├── cmake_install.cmake
├── compile_commands.json
└── decoder

**Comment by presburger** [comment]
decoder.command是MAC上的点击脚本，现在已经不需要了

**Comment by guohui-ma** [comment]
那现在的使用流程是什么呢？直接双击decoder吗？

**Comment by gui0506** [comment]
请问可以麻烦更新一下文档吗？双击decoder出现权限错误
