### ISSUE TITLE
我想请教一下破解经过,,,Orz

### ISSUE THREAD

**Issue by BoilingBlues** [Presburger/qmc-decoder#37]
我读了一遍源码，之前没有接触过破解和加密，在网上找了一下，应该是异或加解密，我想问一下，头文件里的密钥字节表和循环规律是怎么得到的，是逆向工程(安卓还是PC)，还是对比原文件和加密文件？拜托了

**Comment by Leroscox** [comment]
**非作者回复**，私以为对比这种二进制的原文件和加密后的文件摸索加密算法似乎不太现实（也并非完全不可行），所以猜测是通过**逆向工程**或**相关人员泄漏**获得。
