### ISSUE TITLE
Linux下不能转换qmcflac格式

### ISSUE THREAD

**Issue by skykeyjoker** [Presburger/qmc-decoder#42]

**Comment by tomty89** [comment]
已修复：https://github.com/Presburger/qmc-decoder/commit/776fd9c3aa252ea189d1dffb9a719a419c993c38

编译master即可

**Comment by presburger** [comment]
谢谢 @tomty89 ，最近一直在解决ubuntu下mingw下编译的window exe，open函数的UTF8问题。
