### ISSUE TITLE
文件名中有韩文时无法转换

### ISSUE THREAD

**Issue by untn** [Presburger/qmc-decoder#5]
测试时发现文件名中有韩文时无法转换，比如“벤 (Ben) - Stay”这首歌。“벤 (Ben) ”是歌手名，包含韩文字符，软件读取时变成"? (Ben) ",提示：
decode: .\? (Ben) - Stay.qmc3
qmc file read error

**Comment by presburger** [comment]
OK，我会修复这个bug

**Comment by untn** [comment]
新版本韩文文件名还是有问题，目前软件会闪退，测试文件依然是벤 (Ben) - Stay.qmc3
可以随便找个qmc3重命名为벤 (Ben) - Stay进行测试

**Comment by untn** [comment]
新版本韩文文件名还是有问题，目前软件会闪退，测试文件依然是벤 (Ben) - Stay.qmc3
可以随便找个qmc3重命名为벤 (Ben) - Stay进行测试

**Comment by untn** [comment]
> OK，我会修复这个bug

新版本韩文文件名还是有问题，目前软件会闪退，测试文件依然是벤 (Ben) - Stay.qmc3
可以随便找个qmc3重命名为벤 (Ben) - Stay进行测试

**Comment by untn** [comment]
新版本韩文文件名还是有问题，目前软件会闪退，测试文件依然是벤 (Ben) - Stay.qmc3
可以随便找个qmc3重命名为벤 (Ben) - Stay进行测试

**Comment by presburger** [comment]
ok,最近会考虑修复，最近工作有点忙发自我的华为平板电脑-------- 原始邮件 --------主题：Re: [Presburger/qmc-decoder] 文件名中有韩文时无法转换 (#5)发件人：untn 收件人：Presburger/qmc-decoder 抄送：presburger ,Comment 新版本韩文文件名还是有问题，目前软件会闪退，测试文件依然是벤 (Ben) - Stay.qmc3

可以随便找个qmc3重命名为벤 (Ben) - Stay进行测试

**Comment by presburger** [comment]
谢谢你的反馈，本周末我会尝试修复，最近工作较忙，请见谅。发自我的华为平板电脑-------- 原始邮件 --------主题：Re: [Presburger/qmc-decoder] 文件名中有韩文时无法转换 (#5)发件人：untn 收件人：Presburger/qmc-decoder 抄送：presburger ,Comment 新版本韩文文件名还是有问题，目前软件会闪退，测试文件依然是벤 (Ben) - Stay.qmc3

可以随便找个qmc3重命名为벤 (Ben) - Stay进行测试

**Comment by coderstory** [comment]
还未修复 。。。

**Comment by einverne** [comment]
我自己的 build 的二进制，似乎在处理韩文上没有问题。

![screenshot-area-2019-07-27-094151](https://user-images.githubusercontent.com/1962738/61988368-ea867d00-b052-11e9-8687-e19fdd9ccbb8.png)

**Comment by qjhuang810** [comment]
> 还未修复 。。。

你把韩文删掉试试 亲测有效

**Comment by Leroscox** [comment]
已尝试解决该问题，相关代码已在[此 PR 中](https://github.com/Presburger/qmc-decoder/pull/31)。
