### ISSUE TITLE
如何编译成exe文件

### ISSUE THREAD

**Issue by ziyouxiaozi** [Presburger/qmc-decoder#8]
如何编译成exe文件

**Comment by b1llow** [comment]
按照 readme 来不能编译吗？

**Comment by ziyouxiaozi** [comment]
没编译成功，能具体说下怎么编译吗？

**Comment by ziyouxiaozi** [comment]
我用vs编译不得？

**Comment by presburger** [comment]
CMake安装了没？

**Comment by b1llow** [comment]
首先得有 cmake 和 vs （最少得有 c++ build tool）

在 `x86 Native Tools Command Prompt for VS 2017` 这个里面执行 

```
mkdir build
cd build
cmake
msbuild /p:Platform="Win32" qmc-decoder.sln
```

应该就可以编译了。或者也可以用 vs 打开这个qmc-decoder.sln

奇怪，这里 platform 只有 Win32 但是默认是 x86
所以加这么个参数
